// Loads environment variables (like DATABASE_URL) from the .env file
// into process.env
import "dotenv/config";
// Imports the PrismaClient generated by "prisma generate" from schema.prisma
import { PrismaClient } from "./generated/prisma/client";
// Adapter that connects Prisma to MySQL/MariaDB
// (it's the official adapter for both MySQL and MariaDB)
import { PrismaMariaDb } from "@prisma/adapter-mariadb";

let adapter: PrismaMariaDb;
if (process.env.DATABASE_URL) {
  // Creates the adapter with the connection string from .env
  // (e.g.: mysql://blog_user:senha@localhost:3306/bloggers)
  adapter = new PrismaMariaDb(process.env.DATABASE_URL);
}
else {
  // If .env has no DATABASE_URL, the app should not even start
  throw new Error("DATABASE_URL não está definida no .env")
}

// Exports the Prisma client configured with the adapter.
// Every file that needs to talk to the database imports from here,
// ensuring we use a SINGLE connection instance (singleton pattern).
export const prisma = new PrismaClient({ adapter })